name: Scheduled test

on:   
  schedule:
    - cron: "5 5 * * *"

permissions:
  contents: read

jobs:
  call-reusable-test:
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit 
    
